### ISSUE TITLE
`&push&record` on iphone (Chrome and Brave): control bar hidden behind "Downloading" browser bar

### ISSUE THREAD

**Issue by onnozweers** [steveseguin/vdo.ninja#1200]
Hi,

Thanks a lot for this amazing software! I've been doing many live streams with vdo.ninja. Now I'm checking how I can record the livestream also on my own phone, with a higher resolution than the mobile data network allows. So I'm playing with `&record` and `&autorecordlocal`.

I have a problem though. When you locally record your own video, the browser will display a "Downloading" bar, that overlaps the control bar of vdo.ninja. Especially the record button is hidden and can't be reached. Scrolling doesn't help. When I try to get to the button to stop recording, I often lose the download or interrupt the live stream. So I desperately need a way to get to the control bar.

I'll include a screen shot so you can see what I mean.

When I click on the browser's button to cancel download, the browser's "Downloading" bar disappears and I can see the "Stop recording" button, but then video is lost.

So I hope there's a fix for this!

<img src="https://github.com/user-attachments/assets/643fe273-8e48-4322-93a0-8c089bad8593" width=50% height=50%>

After cancelling the download, I can finally see the "Record" button:

<img src="https://github.com/user-attachments/assets/cfe59ccf-e63b-4100-8e4b-6efb0b2875ba" width=50% height=50%>

**Comment by steveseguin** [comment]
This is on an iPhone?

I do recall the iPhone having issues recording locally.  Recording in chunks with `&splitrecording` might be a temporary solution, but what I can do is take another stab at trying to get it working reliably. I didn't have AI previously, so, maybe it can help reveal a solution.

**Comment by onnozweers** [comment]
iPhone indeed. Recording seems to work, though I haven't tested it for long streams yet. I have copied some of the test recordings over and viewed them on my laptop.
It's only when I try to reach the buttons that awkward things happen. I'd like to be able to use the record button, because sometimes very, hm, interesting things happen in my livestreams and I'd like to save such special moments in high quality.
I had seen `&splitrecording` in the manual and will check it out.

**Comment by steveseguin** [comment]
Thank you for that clarification.

I spend a bit of time on the button bar, specifically for mobile.  It needs some improvement anyways

As per iPhones and reliability, I think there's a memory limit set by Safari, and if it goes beyond that, or if the disk space drops below a certain point, it will silently kill the recording -- no error. That was a long while since I last looked at the issue though - it might have resolved itself.

**Comment by onnozweers** [comment]
I can use any browser, that's not a problem. If one browser is preferred I will gladly use that one. But switching phones is way more difficult and costly. I've understood from some people that Chrome is the best browser for vdo.ninja, is that correct?

As for reliability of the recording, well, at the moment the first hurdle is that I can't reach the "record" button in the control bar. I need that button to properly close and save the recording. That is my blocker at the moment.

**Comment by onnozweers** [comment]
Would it be an idea to have an option to put the control bar at the top instead of at the bottom? That shouldn't be too difficult, and it might be sufficient to expose all the buttons.

**Comment by steveseguin** [comment]
I'll work on something now

**Comment by steveseguin** [comment]
For some reason I dont see the download bar in my online test device. I have some iphones local I can use also though.


What version of iOS are you using specifically? what model of iphone? is this Safari?

Something to note about iOS devices is all the browsers are mostly the same -- Apple forbid third party browser engines (at least outside of the EU), so pretty much all browsers are Safari (webkit) with a skin.  No "chromium" browser exists on iOS that I know of.


![Image](https://github.com/user-attachments/assets/ec8b8068-b773-4f66-9cbc-86ee519e8e41)

**Comment by onnozweers** [comment]
Ah, I see, I didn't know these browsers are forced to use the same engine.

I guess you used Safari for that screenshot? I just tried with Safari and indeed, there is no "Downloading" bar that overlaps the control bar! I can reach the "Record" button. Looks good!

Trying to access the recordings now. My iCloud Drive is full, I guess I have to do some cleaning up before I can see them there.

**Comment by steveseguin** [comment]
While Chrome or Edge is normally recommended, Safari is recommend on iOS.  I'm not able replicate that issue with Chrome on iOS however either, so a bit odd.

> Ah, I see, I didn't know these browsers are forced to use the same engine.
> 
> I guess you used Safari for that screenshot? I just tried with Safari and indeed, there is no "Downloading" bar that overlaps the control bar! I can reach the "Record" button. Looks good!
> 
> Trying to access the recordings now. My iCloud Drive is full, I guess I have to do some cleaning up before I can see them there.

**Comment by onnozweers** [comment]
I use an iphone 13 pro with iOS 18.5.

Still struggling to reach the downloaded recordings outside of the Safari browser... And if I click on them in Safari, it opens them as HTML pages!  🙀 With gibberish of course. Could this be a mime type issue?

**Comment by onnozweers** [comment]
Two screenshots to show that Safari treats the downloads as HTML.

![Image](https://github.com/user-attachments/assets/9e56ea09-5015-4b80-bae4-e7f9e740bf46)

![Image](https://github.com/user-attachments/assets/871ea50c-d706-433b-be42-ab70fff2968d)

**Comment by steveseguin** [comment]
Thank you for that.  This might be due to how I trick the browser into letting me stream a local file to disk ,as if its downloading endlessly from a remote site. 

eg: https://github.com/steveseguin/StreamSaver.js/blob/master/mitm.html


I might be able to solve this with a different download/streaming method, but it also likely means I can't enable automatic recordings.

**Comment by onnozweers** [comment]
I removed all photos and videos from my iCloud drive to have plenty of space available. I also removed them locally on the iPhone. I configured the download folder for Safari to a local "Safari" folder (not on iCloud Drive). I restarted the phone. I made fresh recordings, and then saved them locally. But even then, I still can't access the recorded videos outside of Safari. The folder I created for the downloads looks empty when I open it in the file browser. I'm completely puzzled.

With Chrome and Brave I don't have any problems to access the downloaded recordings, and to open them as videos.

**Comment by steveseguin** [comment]
https://vdo.ninja/alpha/?menuoffset&push=GFajvy6

I added `&menuoffset` to alpha, which will let you set an offset from the bottom.

&menuoffset=100px is the default, but you can do `&menuoffset=250px` if you wanted more room, for example.  This is only on vdo.ninja/alpha/ , for testing.  It should give you lots of space between the bottom.

If I can think of a better way of solving this, I'll use that instead.

Thank you kindly for the bug report.

> I removed all photos and videos from my iCloud drive to have plenty of space available. I also removed them locally on the iPhone. I configured the download folder for Safari to a local "Safari" folder (not on iCloud Drive). I restarted the phone. I made fresh recordings, and then saved them locally. But even then, I still can't access the recorded videos outside of Safari. The folder I created for the downloads looks empty when I open it in the file browser. I'm completely puzzled.
> 
> With Chrome and Brave I don't have any problems to access the downloaded recordings, and to open them as videos.

**Comment by steveseguin** [comment]
![Image](https://github.com/user-attachments/assets/cc9d50cc-ebf0-424a-94d1-603eab7eaf42)

**Comment by onnozweers** [comment]
Thanks! Will test very soon.

**Comment by onnozweers** [comment]
It doesn't seem to do anything for me. I tried with Chrome, Brave, Firefox and Safari on iPhone. For example: https://vdo.ninja/alpha/?menuoffset=350px&push=[redacted]&record

The menu bar is always at the bottom. Even with 350px. I tried some other variations but it never seems to move.

**Comment by onnozweers** [comment]
Any idea why `&menuoffset` doesn't work on iPhone?

It does work when I open the same link in Brave on my MacOS.

**Comment by steveseguin** [comment]
Apologies for my delay.  There could be a conflict with some CSS styles at certain screen resolutions, where a different style might have been overriding it.

I pushed a change to production and to alpha related to this feature.  On my iPhone 11, it appears to work, but if it doesn't work for you still, see if you can hard reload the page in your mobile safari, and if it still doesn't work, I'll test more iPhone models to see if the issue appears with other resolutions.

**Comment by onnozweers** [comment]
I think I found it. The CSS was one DIV too deep. It was set in "subControlButtons", but it works when I set it in "controlPositioning".

<img width="854" height="94" alt="Image" src="https://github.com/user-attachments/assets/d444da2b-caaf-4bbb-96d6-5c194b7ecaab" />

Had to figure out how to debug Safari for iPhone 😸

**Comment by steveseguin** [comment]
Wonderful. If that fixes the issue for you, I've just now pushed a change to alpha and production that does that also

```
if (urlParams.has("menuoffset")) {
	getById("subControlButtons").style.bottom = urlParams.get("menuoffset") || "50px";
	getById("controlPositioning").style.bottom = urlParams.get("menuoffset") || "50px";
	getById("subControlButtons").style.setProperty("position", "absolute", "important");
}
```

If you think something else here would work instead, let me know what; other, it is currently working for me so I hope it's also good on your end.

**Comment by onnozweers** [comment]
Awesome! In Safari on iPhone it now works! In Brave on iPhone it doesn't work yet; will try to investigate later.

**Comment by onnozweers** [comment]
I tested again: the `&menuoffset` works in Safari, Chrome and Brave on iPhone.

However, I still face some obstacles: 
* In Brave and Chrome, when I press the `record` button, a download is initiated, but it remains stuck at 0 bytes. This is new. This worked when I opened this issue.
* In Firefox, the `record` button does not do anything. No download is offered.
* In Safari, the download is started, and I can see the file grow. However, I still can't open the file because it looks like gibberish (see earlier screenshot). And I can't save the download to my files. Whatever I do, it does not appear in the filesystem. This is the same as described above.

So, I still have no way to record videos. If only one browser would work flawlessly, I'd be very happy.

**Comment by onnozweers** [comment]
Hi Steve,

I'm still unable to record anything. I just tested again (in alpha and stable)
* With Safari, I can record video but not open the resulting file. Safari regards the files as text file, and I can't find the recordings anywhere with the Files app, nor in iCloud.
* With Chrome, the recording seems stuck at 0 bytes.
* See also previous comment.

Any suggestions?

**Comment by steveseguin** [comment]
Thank you for following up on this issue. 

Root Cause & Solution

  **The Issue:**
  iOS Safari/Chrome have two problems with recording downloads:
  1. Safari: Service workers don't properly set Content-Type headers, causing files to save as .html
  2. Chrome iOS: Shows 0 bytes due to WebKit streaming limitations

  **Why It's Challenging to fix:**
  - iOS doesn't support WebM format (only MP4)
  - StreamSaver.js relies on service workers which iOS handles poorly
  - Blob fallback (storing in memory) can crash the browser on long recordings

  **Solution Now Implemented:**
  I've pushed a fix that:
  - Re-enables blob fallback specifically for iOS devices
  - Auto-enables 5-minute split recording to prevent memory crashes
  - Properly sets MP4 format for iOS
  - Shows a clear warning to iOS users about the split recordings

  **What This Means:**
  - ✅ Files now download with correct .mp4 extension
  - ✅ No more 0-byte files
  - ✅ Recordings split every 5 minutes to prevent crashes
  - ✅ Google Drive uploads continue working normally

  **Joining Split Files:**
```
  ### Using FFmpeg (Mac/Linux/Windows)
  ffmpeg -i "concat:part1.mp4|part2.mp4|part3.mp4" -c copy output.mp4
```

  ### Or create a file list
```
  ls *.mp4 | sed 's/^/file /' > list.txt
  ffmpeg -f concat -safe 0 -i list.txt -c copy output.mp4
```
  **Testing:**
  Please test with the latest version, hosted at https://vdo.ninja/alpha/, and let me know if recordings now work properly on your iOS devices. The split recording is automatic when iOS is detected. I'll follow up with my own testing also.

  **Google Drive Recording Option Note:**
  If you're using the `&gdrive` parameter, your recordings will upload as a single complete file to Google Drive,
  even though local downloads are split. This gives iOS users a way to get the full recording without stitching -
  just download it from Google Drive after recording completes.

**Comment by onnozweers** [comment]
Thanks!

It seems to work now with Safari on iOS. When I start the recording, there is no dialogue; the dialogue asking whether I want to save the file, appears when I stop the recording. This is different than before but it's fine. I get WebM files, which is not what you wrote above. I can access the WebM files after I save them from Safari to my iCloud drive. I can then download them to my laptop and play them. So, it seems I have a working solution!

I tried also Firefox but that does not work properly, I get some files but not WebM or MP4 and they are way too small. That doesn't matter to me; I'll just pick the browser that works best, and in this case that seems to be Safari.

Thanks a lot for your work on this!

I'll do some more testing soon (like, longer than 5 minutes to see what happens).

**Comment by steveseguin** [comment]
Thank you for the update. I'll need to find time to push alpha into production ..
